l_german:
 SETTING_HINTS:0 "Hinweise"
 SETTING_LAST_HOST:0 "Letzter Host"
 SETTING_LAST_PLAYER:0 "Letzter Spieler"
 SETTING_DIFFICULTY:0 "Schwierigkeit"
 SETTING_AUTOSAVE:0 "Auto. speichern"
 SETTING_DEBUG_SAVES:0 "Anzahl an Debug-Speicherständen"
 SETTING_WINDOW_MOVE_TIME:0 "Bewegungszeit des Fensters"
 SETTING_RADIAL_STAY_TIME:0 "Radial stay time"
 SETTING_CAMERA_FACE_NORTH:0 "Kamera nach Norden ausrichten"
 SETTING_AUTOSAVE_TO_CLOUD:0 "Auto. speichern in die Cloud"
 SETTING_DISABLED_ALERTS:0 "Mitteilungen deaktivieren"
 SETTING_DISABLED_HINTS:0 "Hinweise deaktivieren"
 SETTING_FOCUS_ON_COMBAT:0 "Auf Kämpfe fokussieren"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "Legt fest, ob die Spielgeschwindigkeit bei der Beobachtung eines Kampfes verringert werden soll."
 SETTING_PROVINCE_NAMES:0 "Provinznamen"
 SETTING_MAX_TICKS_AHEAD:0 "Max. Ticks voraus"
 MAPNAME_MODE_ALWAYS_ON:0 "Immer an"
 MAPNAME_MODE_ALWAYS_OFF:0 "Immer aus"
 MAPNAME_MODE_MOUSE_OVER:0 "Mouseover"
 MAPNAME_MODE_DEFAULT:0 "Standard"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "Unpassierbares Gelände färben"
 SETTING_PAUSE_ON_EVENTS:0 "Pause bei Ereignissen"
 SETTING_ADVICE:0 "Hinweise bei Benachrichtigungen"
 SETTING_ADVICE_TOOLTIP:0 "Legt fest, ob Hinweise und Hervorhebungen angezeigt werden, wenn auf ein Benachrichtigungssymbol geklickt wird"
  # Map
 SETTING_DRAW_TERRAIN:0 "Terrain"
 SETTING_DRAW_WATER:0 "Wasser"
 SETTING_DRAW_BORDERS:0 "Grenzen"
 SETTING_DRAW_TREES:0 "Bäume"
 SETTING_DRAW_RIVERS:0 "Flüsse"
 SETTING_DRAW_POSTFX:0 "Postfx"
 SETTING_DRAW_SKY:0 "Himmel"
 SETTING_DRAW_BLOOM:0 "Bloom"
 SETTING_DRAW_TOOLTIPS:0 "Tooltips"
 SETTING_DRAW_CITYSPRAWL:0 "Städte"
 SETTING_DRAW_SHADOWS:0 "Schatten"
  # Outliner
 SETTING_OUTLINER_SHOW_OUTLINER:0 "Schnellauswahl zeigen"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "Armeen des Spielers zeigen"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "Flotten des Spielers zeigen"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "Flotten des Spielers zeigen"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "Flotten des Spielers zeigen"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "Flotten des Spielers zeigen"
 SETTING_OUTLINER_COMBATS:0 "Kämpfe zeigen"
 SETTING_OUTLINER_SIEGES_OUR:0 "Unsere Belagerungen zeigen"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "Feindliche Belagerungen zeigen"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "Illoyale Charaktere zeigen"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "Gebäude im Bau zeigen"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "Militär im Bau zeigen"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "Territoriumsverbesserungen zeigen"
 SETTING_OUTLINER_ACTIVE_WARS:0 "Aktive Kriege zeigen"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "Aktive Diplomatie zeigen"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "Menschliche Spieler zeigen"
