l_simp_chinese:
 SETTING_HINTS:0 "提示"
 SETTING_LAST_HOST:0 "上一名房主"
 SETTING_LAST_PLAYER:0 "上一名玩家"
 SETTING_DIFFICULTY:0 "难度"
 SETTING_AUTOSAVE:0 "自动保存间隔"
 SETTING_DEBUG_SAVES:0 "调试存档数量"
 SETTING_WINDOW_MOVE_TIME:0 "窗口移动时间"
 SETTING_RADIAL_STAY_TIME:0 "径向停留时间"
 SETTING_CAMERA_FACE_NORTH:0 "视角朝北"
 SETTING_AUTOSAVE_TO_CLOUD:0 "自动保存至云端"
 SETTING_DISABLED_ALERTS:0 "禁用警告"
 SETTING_DISABLED_HINTS:0 "关闭提示"
 SETTING_FOCUS_ON_COMBAT:0 "专注于战斗"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "决定观察战斗时是否应限制游戏速度。"
 SETTING_PROVINCE_NAMES:0 "省份名称"
 SETTING_MAX_TICKS_AHEAD:0 "最大领先 ticks"
 MAPNAME_MODE_ALWAYS_ON:0 "始终开启"
 MAPNAME_MODE_ALWAYS_OFF:0 "始终关闭"
 MAPNAME_MODE_MOUSE_OVER:0 "鼠标悬停"
 MAPNAME_MODE_DEFAULT:0 "默认"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "填充不可通行的地形"
 SETTING_PAUSE_ON_EVENTS:0 "触发事件时暂停"
 SETTING_ADVICE:0 "警示建议"
 SETTING_ADVICE_TOOLTIP:0 "设置点击警示图标时，是否显示高亮和建议"
  # Map
 SETTING_DRAW_TERRAIN:0 "绘制地形"
 SETTING_DRAW_WATER:0 "绘制水域"
 SETTING_DRAW_BORDERS:0 "绘制边界"
 SETTING_DRAW_TREES:0 "绘制树木"
 SETTING_DRAW_RIVERS:0 "绘制河流"
 SETTING_DRAW_POSTFX:0 "绘制后期效果"
 SETTING_DRAW_SKY:0 "绘制天空"
 SETTING_DRAW_BLOOM:0 "绘制花卉"
 SETTING_DRAW_TOOLTIPS:0 "绘制工具提示"
 SETTING_DRAW_CITYSPRAWL:0 "绘制城市扩张"
 SETTING_DRAW_SHADOWS:0 "绘制阴影"
  # Outliner
 SETTING_OUTLINER_SHOW_OUTLINER:0 "显示概览窗口"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "显示玩家陆军"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "显示玩家海军"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "显示玩家海军"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "显示玩家海军"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "显示玩家海军"
 SETTING_OUTLINER_COMBATS:0 "显示战斗"
 SETTING_OUTLINER_SIEGES_OUR:0 "显示我们的围攻"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "显示敌军围攻"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "显示不忠的人物"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "显示建筑工程"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "显示军队建设"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "显示领土发展"
 SETTING_OUTLINER_ACTIVE_WARS:0 "显示进行中的战争"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "显示进行中的外交"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "显示玩家"
