l_french:
 SETTING_HINTS:0 "Astuces"
 SETTING_LAST_HOST:0 "Dernier hébergé"
 SETTING_LAST_PLAYER:0 "Dernier joueur"
 SETTING_DIFFICULTY:0 "Difficulté"
 SETTING_AUTOSAVE:0 "Sauvegardes automatiques"
 SETTING_DEBUG_SAVES:0 "Nbre de sauv. de débogage"
 SETTING_WINDOW_MOVE_TIME:0 "Vitesse de déplacement des fenêtres"
 SETTING_RADIAL_STAY_TIME:0 "Latence radiale"
 SETTING_CAMERA_FACE_NORTH:0 "Caméra vers le nord"
 SETTING_AUTOSAVE_TO_CLOUD:0 "Sauvegarde automatique sur le cloud"
 SETTING_DISABLED_ALERTS:0 "Alertes désactivées"
 SETTING_DISABLED_HINTS:0 "Astuces désactivées"
 SETTING_FOCUS_ON_COMBAT:0 "Centrer sur les batailles"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "Détermine si la vitesse du jeu doit ralentir en cas d'observation d'un combat."
 SETTING_PROVINCE_NAMES:0 "Noms des provinces"
 SETTING_MAX_TICKS_AHEAD:0 "Maximum de ticks d'avance"
 MAPNAME_MODE_ALWAYS_ON:0 "Toujours"
 MAPNAME_MODE_ALWAYS_OFF:0 "Jamais"
 MAPNAME_MODE_MOUSE_OVER:0 "Autour du curseur"
 MAPNAME_MODE_DEFAULT:0 "Par défaut"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "Coloration du terrain infranchissable"
 SETTING_PAUSE_ON_EVENTS:0 "Pause lors des événements"
 SETTING_ADVICE:0 "Conseils dans les alertes"
 SETTING_ADVICE_TOOLTIP:0 "Détermine si les conseils et mises en garde seront affichés au moment de cliquer sur les icônes des alertes."
  # Map
 SETTING_DRAW_TERRAIN:0 "Afficher le terrain"
 SETTING_DRAW_WATER:0 "Afficher l'eau"
 SETTING_DRAW_BORDERS:0 "Afficher les frontières"
 SETTING_DRAW_TREES:0 "Afficher les arbres"
 SETTING_DRAW_RIVERS:0 "Afficher les cours d'eau"
 SETTING_DRAW_POSTFX:0 "Afficher le postfx"
 SETTING_DRAW_SKY:0 "Afficher le ciel"
 SETTING_DRAW_BLOOM:0 "Afficher le flou lumineux"
 SETTING_DRAW_TOOLTIPS:0 "Afficher les infobulles"
 SETTING_DRAW_CITYSPRAWL:0 "Afficher l'extension des cités"
 SETTING_DRAW_SHADOWS:0 "Afficher les ombres"
  # Outliner
 SETTING_OUTLINER_SHOW_OUTLINER:0 "Affiche le gestionnaire"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "Affiche les armées du joueur"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "Affiche les flottes du joueur"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "Affiche les flottes automatisées du joueur"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "Affiche les armées automatisées du joueur"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "Affiche les armées provinciales du joueur"
 SETTING_OUTLINER_COMBATS:0 "Affiche les batailles"
 SETTING_OUTLINER_SIEGES_OUR:0 "Affiche les sièges que nous menons"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "Affiche les sièges menés contre nous"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "Affiche les personnages déloyaux"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "Affiche les constructions en cours"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "Affiche les constructions militaires"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "Affiche les améliorations des localités"
 SETTING_OUTLINER_ACTIVE_WARS:0 "Affiche les guerres en cours"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "Affiche les relations diplomatiques en cours"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "Affiche les joueurs"

# === [LocEditor:OrphanedKeys] Keys that do not exist in English ===
 SETTING_DIFFICULTY_TOOLTIP:0 "Réglage de la difficulté du jeu."
