l_spanish:
 SETTING_HINTS:0 "Pistas"
 SETTING_LAST_HOST:0 "Último anfitrión"
 SETTING_LAST_PLAYER:0 "Último jugador"
 SETTING_DIFFICULTY:0 "Dificultad"
 SETTING_AUTOSAVE:0 "Intervalo de guardado automático"
 SETTING_DEBUG_SAVES:0 "Cantidad de guardados de depuración de errores"
 SETTING_WINDOW_MOVE_TIME:0 "Tiempo de movimiento de ventana"
 SETTING_RADIAL_STAY_TIME:0 "Tiempo de permanencia radial"
 SETTING_CAMERA_FACE_NORTH:0 "La cámara apunta al norte"
 SETTING_AUTOSAVE_TO_CLOUD:0 "Guardar automáticamente en la nube"
 SETTING_DISABLED_ALERTS:0 "Alertas desactivadas"
 SETTING_DISABLED_HINTS:0 "Pistas desactivadas"
 SETTING_FOCUS_ON_COMBAT:0 "Centrarse en el combate"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "Determina si se debe restringir la velocidad del juego al observar un combate."
 SETTING_PROVINCE_NAMES:0 "Nombres de provincias"
 SETTING_MAX_TICKS_AHEAD:0 "Cantidad máxima de unidades de tiempo"
 MAPNAME_MODE_ALWAYS_ON:0 "Siempre activado"
 MAPNAME_MODE_ALWAYS_OFF:0 "Siempre desactivado"
 MAPNAME_MODE_MOUSE_OVER:0 "Cursor del mouse"
 MAPNAME_MODE_DEFAULT:0 "Predeterminado"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "Rellenar terreno impasable"
 SETTING_PAUSE_ON_EVENTS:0 "Pausa en eventos"
 SETTING_ADVICE:0 "Consejos en alertas"
 SETTING_ADVICE_TOOLTIP:0 "Determina si se mostrarán consejos y datos destacados cuando hagas clic en el ícono de una alerta"
  # Map
 SETTING_DRAW_TERRAIN:0 "Dibujar terreno"
 SETTING_DRAW_WATER:0 "Dibujar agua"
 SETTING_DRAW_BORDERS:0 "Dibujar fronteras"
 SETTING_DRAW_TREES:0 "Dibujar árboles"
 SETTING_DRAW_RIVERS:0 "Dibujar ríos"
 SETTING_DRAW_POSTFX:0 "Dibujar efectos postprocesado"
 SETTING_DRAW_SKY:0 "Dibujar cielo"
 SETTING_DRAW_BLOOM:0 "Dibujar efecto de luz"
 SETTING_DRAW_TOOLTIPS:0 "Dibujar descripciones emergentes"
 SETTING_DRAW_CITYSPRAWL:0 "Dibujar extensión de ciudades"
 SETTING_DRAW_SHADOWS:0 "Dibujar sombras"
  # Outliner
 SETTING_OUTLINER_SHOW_OUTLINER:0 "Mostrar resumen"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "Mostrar ejércitos de jugador"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "Mostrar armadas de jugador"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "Mostrar armadas de jugador"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "Mostrar armadas de jugador"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "Mostrar armadas de jugador"
 SETTING_OUTLINER_COMBATS:0 "Mostrar combates"
 SETTING_OUTLINER_SIEGES_OUR:0 "Mostrar nuestros asedios"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "Mostrar asedios hostiles"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "Mostrar personajes desleales"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "Mostrar construcciones de edificaciones"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "Mostrar construcciones militares"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "Mostrar mejoras del territorio"
 SETTING_OUTLINER_ACTIVE_WARS:0 "Mostrar guerras activas"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "Mostrar diplomacia activa"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "Mostrar jugadores humanos"
